### ENV
#
# WEBSERVER_FQDN
#
version: '3.8'

services:
  mongo-express:
    image: mongo-express
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    networks:
      - web
    deploy:
       mode: replicated
       replicas: 1
       #placement:
       # constraints:
       #   - node.labels.database == true
       labels:
       - traefik.enable=true
       - traefik.port=8081
       - traefik.frontend.rule=Host:${WEBSERVER_FQDN}
       - traefik.protocol=http
       - traefik.docker.network=web
